title: Wei Jingyu
description: Just some notes.
pin:  In the depths of winter I finally learned there was in me an invincible summer.
url: weijingyu.com
permalink: pretty
timezone: Asia/Shanghai
pagination: false
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
  - quotes
